universe = vanilla
executable = /usr/bin/cat
Arguments = /gpfs/mskmind_ess/rosed2/Hackathon/gpu-test.py

# "short", "medium", "long" for jobs lasting
# ~12 hr, ~24 hr, ~7 days
+GPUJobLength = "short"

request_gpus = 1
request_memory = 1GB
#request_cpus = 1
#request_disk = 10MB

output = /gpfs/mskmind_ess/rosed2/$(Cluster)_$(Process).out
log = $(Cluster)_$(Process).log
error = $(Cluster)_$(Process).err

# number of jobs to submit
queue 1

